version: "3.7"

services:
    api:
        build: ./api
        image: ezsetup_api:latest
        env_file: .env
        ports:
            - "5002:5000"
        depends_on:
            - database
            - cache
        restart: always
    worker:
        build:
            context: ./api
            dockerfile: Dockerfile.worker
        image: ezsetup_worker:latest
        env_file: .env
        depends_on:
            - cache
        restart: always
    frontend:
        build: ./frontend
        image: ezsetup_frontend:latest
        env_file: .env
        ports:
            - "80:8080"
        depends_on:
            - api
        restart: always
    cache:
        image: redis:3.2
        env_file: .env
        ports:
            - "${REDIS_PORT}:6379"
        restart: always
    database:
        image: postgres:9.6
        env_file: .env
        environment:
            - PGDATA=/var/lib/postgresql/data/ezsetup
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./.pgdata:/var/lib/postgresql/data/ezsetup
            - ./api/database/migrations:/docker-entrypoint-initdb.d
        restart: always
