version: 2
jobs:
    api-unittest:
        docker:
            - image: circleci/python:3.6
              environments:
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456
                  - POSTGRES_HOST: 127.0.0.1
                  - POSTGRES_PORT: 5432
                  - POSTGRES_POOL_MIN_CONN: 10
                  - POSTGRES_POOL_MIN_CONN: 100
                  - REDIS_HOST: 127.0.0.1
                  - REDIS_PORT: 6379
                  - REDIS_TOKEN_DB: 1

            - image: nguyendv/ezsetup-pg-dev:latest
              environments:
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456
            - image: redis:3.2

        steps:
            - checkout
            - run: sudo pip install -r api/requirements-test.txt
            - run: mypy --ignore-missing-imports api/app.py
            - run: mypy --ignore-missing-imports api/tests
            - run: pytest api/

workflows:
    version: 2
    test:
        jobs:
            - api-unittest

