version: 2
jobs:
    api-unittest:
        docker:
            - image: circleci/python:3.6
              environment:
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456
                  - POSTGRES_HOST: 127.0.0.1
                  - POSTGRES_PORT: 5432
                  - POSTGRES_POOL_MIN_CONN: 10
                  - POSTGRES_POOL_MAX_CONN: 100
                  - REDIS_HOST: 127.0.0.1
                  - REDIS_PORT: 6379
                  - REDIS_TOKEN_DB: 1

            - image: circleci/postgres:9.6
              environment:
                  - POSTGRES_DB: ezsetup
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456

            - image: redis:3.2

        steps:
            - checkout
            - run: | # init database
                    sudo apt install postgresql-client
                    cat api/database/migrations/*.sql | PGPASSWORD=123456 psql -q -h 127.0.0.1 -p 5432 -U ezsetup -d ezsetup
            - run: sudo pip install pipenv
            - run:
                command: |
                    cd api
                    pipenv --python 3.6
                    pipenv install -d
            - run: 
                command: |
                    cd api
                    pipenv run mypy --ignore-missing-imports app.py
                    pipenv run mypy --ignore-missing-imports tests
                    PYTHONPATH=. pipenv run pytest
                    PYTHONPATH=. pipenv run pytest api/

workflows:
    version: 2
    test:
        jobs:
            - api-unittest

